name: Setup kubectl and plugins
description: 'Install a specific version of kubectl and plugins via krew'
branding:
  icon: 'package'
  color: 'blue'
author: Marco Franssen
inputs:
  kubectlVersion:
    description: >-
      The kubectl version you want to use (defaults to latest stable).
    required: false
    default: stable
  enablePlugins:
    description: >-
      Install krew to manage kubectl plugins (defaults to false).
    required: false
    default: 'false'
  plugins:
    description: >-
      Install the given plugins (comma or space separated).
    required: false
    default: ''
outputs:
  kubectl-version:
    description: 'The kubectl version that was installed.'
  krew-version:
    description: 'The krew version that was installed.'
  krew-plugins:
    description: 'The list of installed plugins (json serialized object).'
runs:
  using: 'node16'
  main: 'dist/index.js'
